@startuml
class NamedVariableDrawer {
    + <<override>> OnGUI(position:Rect, property:SerializedProperty, label:GUIContent) : void
    + <<override>> GetPropertyHeight(property:SerializedProperty, label:GUIContent) : float
}
PropertyDrawer <|-- NamedVariableDrawer
@enduml
