@startuml
class MinMaxSliderAttribute {
    + <<readonly>> max : float
    + <<readonly>> min : float
    + MinMaxSliderAttribute(min:float, max:float)
}
PropertyAttribute <|-- MinMaxSliderAttribute
@enduml
