@startuml
class Climb {
    + <<override>> OnStart() : void
    + <<override>> OnStop() : void
    + <<override>> CanStart() : bool
    + <<override>> UpdateAnimatorIK(layer:int) : bool
    + <<override>> UpdateVelocity(velocity:Vector3) : bool
    + <<override>> UpdateRotation() : bool
    + <<override>> CheckGround() : bool
    + <<override>> CheckStep() : bool
}
MotionState <|-- Climb
@enduml
