@startuml
class ItemContainerPopulatorInspector {
    + <<override>> OnInspectorGUI() : void
    + <<override>> UseDefaultMargins() : bool
}
Editor <|-- ItemContainerPopulatorInspector
@enduml
