@startuml
class Cooldown {
    + overlay : Image
    + IsCoolDown : bool <<get>>
    + Update() : void
    + OnPointerClick(eventData:PointerEventData) : void
}
MonoBehaviour <|-- Cooldown
IPointerClickHandler <|-- Cooldown
@enduml
