@startuml
class ContextMenuTrigger {
    + menu : string[]
    + OnPointerDown(eventData:PointerEventData) : void
}
MonoBehaviour <|-- ContextMenuTrigger
IPointerDownHandler <|-- ContextMenuTrigger
@enduml
