@startuml
class RadialMenuTrigger {
    + menuIcons : Sprite[]
    + OnPointerDown(eventData:PointerEventData) : void
}
MonoBehaviour <|-- RadialMenuTrigger
IPointerDownHandler <|-- RadialMenuTrigger
@enduml
