@startuml
!include AudioEventListenerInspector.puml
!include BlackboardInspector.puml
!include CallbackHandlerInspector.puml
!include PropertyBindingInspector.puml
!include SelectionHandlerInspector.puml
@enduml
