@startuml
class SetPositionToTarget {
    + <<override>> OnStart() : void
    + <<override>> OnUpdate() : ActionStatus
    GetClosest(self:Transform, transforms:Transform[]) : Transform
}
Action <|-- SetPositionToTarget
@enduml
