@startuml
class ItemContainerPopulator {
}
class Entry {
    + name : string = "Inventory"
    + group : ItemGroup
}
MonoBehaviour <|-- ItemContainerPopulator
ItemContainerPopulator +-- Entry
@enduml
