@startuml Simple Inventory Manager
/'!include Attributes/dirInclude.puml
!include Equipment Handler/dirInclude.puml
!include Generation/dirInclude.puml
!include Items/dirInclude.puml
!include Modifier/dirInclude.puml
!include Testing/dirInclude.puml
!include Triggers/dirInclude.puml
!include UI/dirInclude.puml
!include AreaOfEffect.puml
!include Category.puml
!include CraftingRecipe.puml
!include CurrencyConversion.puml
!include EquipmentRegion.puml
!include ItemCollectionPopulator.puml
!include ItemCollection.puml
!include ItemCondition.puml
!include ItemContainerPopulator.puml
!include ItemEventData.puml
!include ItemGroup.puml
!include PlaceItem.puml
!include Projectile.puml
!include Rarity.puml
'/

!include Settings/SimpleSettings.puml
!include InventoryManager.puml
!include ItemDatabase.puml

together {
    class ScriptableObject
    class InventoryManager
}
together {
    class Settings
    class ItemDatabase
}

InventoryManager o-- ItemDatabase
InventoryManager o-- Default
InventoryManager o-- UI
InventoryManager o-- Input
InventoryManager o-- SavingLoading
InventoryManager o-- Notifications

@enduml
