@startuml
class CompareNumber {
    + <<override>> OnStart() : void
    + <<override>> OnUpdate() : ActionStatus
}
enum Condition {
    Greater,
    Less,
}
Action <|-- CompareNumber
ICondition <|-- CompareNumber
CompareNumber +-- Condition
@enduml
