@startuml
class ShowProgressbar {
    + <<override>> OnStart() : void
    + <<override>> OnUpdate() : ActionStatus
    + <<override>> OnInterrupt() : void
}
Action <|-- ShowProgressbar
@enduml
