@startuml
!include ApplyRootMotion.puml
!include CrossFade.puml
!include IsInTransition.puml
!include IsName.puml
!include SetBool.puml
!include SetFloat.puml
!include SetInt.puml
!include SetRandomFloat.puml
!include SetTrigger.puml
@enduml
