@startuml
class DisplayCursor {
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerExit(eventData:PointerEventData) : void
}
MonoBehaviour <|-- DisplayCursor
IPointerEnterHandler <|-- DisplayCursor
IPointerExitHandler <|-- DisplayCursor
@enduml
