@startuml
class NamedVariableCollectionEditor {
    + <<override>> ToolbarName : string <<get>>
    + NamedVariableCollectionEditor(serializedObject:SerializedObject, serializedProperty:SerializedProperty)
}
"ObjectCollectionEditor`1" "<NamedVariable>" <|-- NamedVariableCollectionEditor
@enduml
